<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Post extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'body', 'slug', 'image', 'category_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting( function ($post) {
            if ($post->image)
            {
                Storage::disk('public')->delete($post->image);
            }
        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

//    public function getImageAttrebute()
//    {
//        return asset('storage/'. $this->image);
//    }

}
